server:
  host: localhost
  port: 8080
  idle_timeout: 60s
  read_timeout: 10s
  write_timeout: 30s

service:
  archive_directory: archives
  max_active_tasks: 3
  max_files_per_task: 3
  allowed_extensions:
    - .jpg
    - .jpeg
    - .pdf